---
driver:
  name: vagrant
  # Set a custom Vagrantfile so enable Vagrant-Cachier and speed up
  # test kitchen runs.
  vagrantfile_erb: ".kitchen.vagrantfile.erb"
  # This should just be omitted but we need to tell Test Kitchen to
  # download the Chef rpm/deb to the Vagrant-Cachier path
  # See https://github.com/test-kitchen/test-kitchen/issues/440
  require_chef_omnibus: 11.16.4 -d /tmp/vagrant-cache/vagrant_omnibus


provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
    run_list: recipe[build-essential]

suites:
  - name: default
    run_list:
      - recipe[serverdensity-inviqa::default]
    attributes:
  - name: plugin_install
    run_list:
      - recipe[serverdensity-inviqa::plugin_install]
    attributes: